### ISSUE TITLE
トップ画面を作成する

### ISSUE THREAD

**Issue by SatooRu65536** [SystemEngineeringTeam/meibo-system-front#3]
一旦PC画面だけ作成する。mobile は気にしない
データは `usersAtomLoadable` を使用する

`page` ディレクトリはルーティングするだけ
本体は `components/pages` に書く
`components/pages/xxx/index.tsx` はロジックだけで表示はそれ以下の `components/pages/xxx/body.tsx` 等に任せる

**Comment by nasubi916** [comment]
`index.tsx`にて､
`<TopBody key={user.id} user={user} />)}`とあり､このタグを囲む形でflexを書きたいのですが､`components/pages/xxx/index.tsx`にはロジックだけを書くという制約に反してしまいます｡

`body.tsx`に`users`ごと渡していいでしょうか?

**Comment by SatooRu65536** [comment]
> `components/pages/top/index.tsx`にて､ `<TopBody key={user.id} user={user} />)}`とあり､このタグを囲む形でflexを書きたいのですが､`components/pages/xxx/index.tsx`にはロジックだけを書くという制約に反してしまいます｡
> 
> `body.tsx`に`users`ごと渡していいでしょうか?

全然大丈夫 👍
むしろサンプルが良くなくて、そっちの方がいいね！
